# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-02 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdictadas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdictada',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
