# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-02 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AyudanteAcademico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('foto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AyudanteDeberes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('horario', models.CharField(blank=True, max_length=100, null=True)),
                ('foto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('oficina', models.CharField(blank=True, max_length=100, null=True)),
                ('foto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('oficina', models.CharField(blank=True, max_length=100, null=True)),
                ('paralelos', models.CharField(max_length=100)),
                ('foto', models.CharField(max_length=100)),
            ],
        ),
    ]
