# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-02 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayudanteacademico',
            name='foto',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ayudantedeberes',
            name='foto',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='coordinador',
            name='foto',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='foto',
            field=models.CharField(max_length=500),
        ),
    ]
