# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-03 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0003_auto_20170303_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='foto',
            field=models.FileField(upload_to=''),
        ),
    ]
