# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-03 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0004_auto_20170303_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayudanteacademico',
            name='foto',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='ayudantedeberes',
            name='foto',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='coordinador',
            name='foto',
            field=models.FileField(upload_to=''),
        ),
    ]
