# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-01 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('requisitos', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='qurso',
        ),
    ]
