# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-02 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_auto_20170301_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='politicas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='syllabus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
