# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-02 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_auto_20170301_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='syllabus',
        ),
        migrations.AddField(
            model_name='materia',
            name='bibliografia',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='escenarios',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='objetivosE',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='objetivosG',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='recursos',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='temas',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='codigo',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='materia',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='materia',
            name='politicas',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='requisitos',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
